/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import Vista.DatosUser;

/**
 *
 * @author VA
 */
public class FrmInvitado extends javax.swing.JFrame {

    /**
     * Creates new form FrmInvitado
     */
    public FrmInvitado() {
        initComponents();   
        this.setLocationRelativeTo(null);
        setResizable(false);
        Correo.hide();
        pass.hide();
        cod.hide();
    }
       
    public JLabel getLabel() {
        return lblNombre;
    }
    public JLabel getLabel1() {
        return Num;
    }
    public JLabel getLabel2(){
        return Marca;
    }
    public JLabel getLabel3(){
        return Procesador;
    }
    public JLabel getLabel4(){
        return Estado;
    }
    public JLabel getLabel5(){
        return Almacenamiento;
    }
    public JLabel getLabel6(){
        return ram;
    }
    public JLabel getLabel7(){
        return mac;
    }
    public JLabel getLabel8(){
        return accesorio;
    }
    public JLabel getLabel9(){
        return Correo;
    }
    public JLabel getLabel10(){
        return pass;
    }
    public JLabel gatLabel11(){
        return cod;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        Num = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();
        Procesador = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        Almacenamiento = new javax.swing.JLabel();
        ram = new javax.swing.JLabel();
        mac = new javax.swing.JLabel();
        accesorio = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        cod = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setText("jLabel1");

        Num.setText("jLabel12");

        Marca.setText("jLabel1");

        Procesador.setText("jLabel2");

        Estado.setText("jLabel3");

        Almacenamiento.setText("jLabel4");

        ram.setText("jLabel5");

        mac.setText("jLabel6");

        accesorio.setText("jLabel7");

        Correo.setRequestFocusEnabled(false);

        pass.setFocusable(false);

        jMenu1.setText("Ingreso");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit.png"))); // NOI18N
        jMenu3.setText("Actualizar correo y clave");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Procesador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Marca)
                            .addComponent(Num)
                            .addComponent(Estado)
                            .addComponent(Almacenamiento)
                            .addComponent(ram)
                            .addComponent(mac)
                            .addComponent(accesorio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                        .addGap(117, 117, 117))))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(lblNombre)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblNombre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Marca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Procesador)
                    .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Estado)
                .addGap(18, 18, 18)
                .addComponent(Almacenamiento)
                .addGap(18, 18, 18)
                .addComponent(ram)
                .addGap(18, 18, 18)
                .addComponent(mac)
                .addGap(18, 18, 18)
                .addComponent(accesorio)
                .addGap(15, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // clic editar
        // pasar correo y clave para actualizacion
        String id = cod.getText(); 
        String correo = Correo.getText(); 
        String password = pass.getText(); 
        DatosUser em = new DatosUser();
        em.actCorreo.setText(correo);
        em.Pass1.setText(password);
        em.Pass2.setText(password);
        em.codAc.setText(id);
        em.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        FrmLogin obj = new FrmLogin();
        JOptionPane.showMessageDialog(null, "Ha finalizado la sesión");            
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Almacenamiento;
    public static javax.swing.JLabel Correo;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel Num;
    private javax.swing.JLabel Procesador;
    private javax.swing.JLabel accesorio;
    public static javax.swing.JLabel cod;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel mac;
    public static javax.swing.JLabel pass;
    private javax.swing.JLabel ram;
    // End of variables declaration//GEN-END:variables
}
