/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.Inventario;
import Dao.DaoInventario;
import javax.swing.JOptionPane;
/**
 *
 * @author LPZ
 */
public class RegistroInv extends javax.swing.JFrame {

    /**
     * Creates new form RegistroInv
     */
    public RegistroInv() {
        super("Registrar equipo para inventario");
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        
    }
    public void convertiraMayusculasEnJtextfield(javax.swing.JTextField jTextfieldS, int pos) {
        String cadena = (jTextfieldS.getText()).toUpperCase();
        jTextfieldS.setText(cadena);
        jTextfieldS.setCaretPosition(pos);
    }
    DaoInventario Linv = new DaoInventario();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CboxMarca = new javax.swing.JComboBox<>();
        CboxProcesador = new javax.swing.JComboBox<>();
        CboxEstado = new javax.swing.JComboBox<>();
        CboxAlmacenamiento = new javax.swing.JComboBox<>();
        CboxMemoriaR = new javax.swing.JComboBox<>();
        CboxAccesorios = new javax.swing.JComboBox<>();
        txtMAC = new javax.swing.JTextField();
        txtCodEquipo = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero del equipo");

        jLabel2.setText("Marca");

        jLabel3.setText("Procesador");

        jLabel4.setText("Estado");

        jLabel5.setText("Almacenamiento");

        jLabel6.setText("Memoria RAM");

        jLabel7.setText("MAC");

        jLabel8.setText("Accesorios");

        CboxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar marca...", "LENOVO", "ACER", "HP", "MSI", "ASUS", "APPLE" }));
        CboxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxMarcaActionPerformed(evt);
            }
        });

        CboxProcesador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione procesador...", "AMD RAYZEN 5 3600", "AMD ATHLON", "AMD SEREA A PRO", "INTEL CORE 5 ", "INTEL CORE 7", "INTEL CORE 9" }));

        CboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el estado...", "Activo", "Inactivo" }));
        CboxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxEstadoActionPerformed(evt);
            }
        });

        CboxAlmacenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el alamcenamiento...", "250 GB", "500 GB", "1 TERA", "2 TERAS" }));

        CboxMemoriaR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "4 GB", "8 GB", "12 GB", "16 GB", "32 GB", "64 GB" }));
        CboxMemoriaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxMemoriaRActionPerformed(evt);
            }
        });

        CboxAccesorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Mouse", "Morral ", "Guaya", "Cargador", "Todos" }));

        txtMAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMACActionPerformed(evt);
            }
        });
        txtMAC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMACKeyReleased(evt);
            }
        });

        txtCodEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodEquipoActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salida (1).png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Registre el equipo del Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CboxAccesorios, javax.swing.GroupLayout.Alignment.TRAILING, 0, 194, Short.MAX_VALUE)
                        .addComponent(txtMAC, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CboxMemoriaR, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CboxAlmacenamiento, javax.swing.GroupLayout.Alignment.LEADING, 0, 194, Short.MAX_VALUE)
                        .addComponent(CboxEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CboxMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CboxProcesador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCodEquipo)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CboxProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CboxAlmacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CboxMemoriaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CboxAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodEquipoActionPerformed

    private void CboxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxEstadoActionPerformed

    private void txtMACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMACActionPerformed
        // TODO add your handling code here:
        txtMAC.setText(txtMAC.getText().toUpperCase());
    }//GEN-LAST:event_txtMACActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // volver
        this.hide();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Guardar datos inventario
        String cb1 = CboxMarca.getSelectedItem().toString();
        String cb2 = CboxProcesador.getSelectedItem().toString();
        String cb3 = CboxEstado.getSelectedItem().toString();
        String cb4 = CboxAlmacenamiento.getSelectedItem().toString();
        String cb5 = CboxMemoriaR.getSelectedItem().toString();
        String cb6 = CboxAccesorios.getSelectedItem().toString();
        if (txtCodEquipo.getText().equals("") || cb1.equals("Seleccionar marca...") || cb2.equals("Seleccione procesador...") || cb3.equals("Seleccione el estado...") 
                || cb4.equals("Seleccione el alamcenamiento...") || cb5.equals("Seleccione...") || txtMAC.getText().equals("") || cb6.equals("Seleccione...") ) {
            JOptionPane.showMessageDialog(null, "Por favor diligencie en su totalidad todos los campos");
            
        } else{
        try {
            Inventario inv=new Inventario();
	    inv.setNumero(Integer.parseInt(txtCodEquipo.getText()));
	    inv.setMarca(CboxMarca.getSelectedItem().toString());
	    inv.setProcesador(CboxProcesador.getSelectedItem().toString());
	    inv.setEstado(CboxEstado.getSelectedItem().toString());
            inv.setAlmacenamiento(CboxAlmacenamiento.getSelectedItem().toString());
            inv.setRam(CboxMemoriaR.getSelectedItem().toString());
            inv.setMac(txtMAC.getText());
            inv.setAccesorios(CboxAccesorios.getSelectedItem().toString());
            Linv.GuardarUsuario(inv);   
            this.hide();
            RegistroUser user =new RegistroUser();
            user.show();
	} catch (Exception ex) {
            System.out.println(ex);
        }
    }    
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void CboxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxMarcaActionPerformed

    private void CboxMemoriaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxMemoriaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxMemoriaRActionPerformed

    private void txtMACKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMACKeyReleased
        // Covertir a mayusculas mientrs escribe
        int pos = txtMAC.getCaretPosition();
        convertiraMayusculasEnJtextfield(txtMAC, pos);
    }//GEN-LAST:event_txtMACKeyReleased

    /**
     * @param args the command line arguments
     */
    /**
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroInv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxAccesorios;
    private javax.swing.JComboBox<String> CboxAlmacenamiento;
    private javax.swing.JComboBox<String> CboxEstado;
    private javax.swing.JComboBox<String> CboxMarca;
    private javax.swing.JComboBox<String> CboxMemoriaR;
    private javax.swing.JComboBox<String> CboxProcesador;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCodEquipo;
    private javax.swing.JTextField txtMAC;
    // End of variables declaration//GEN-END:variables
}
