/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import static com.sun.org.apache.xpath.internal.XPath.SELECT;
import static javax.swing.text.html.HTML.Tag.SELECT;
import Dao.DaoUsuario;
import Modelo.Usuario;
import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Germancho
 */
public class VerUSers extends javax.swing.JFrame {  
    
    DefaultTableModel modelo = new DefaultTableModel();
    DaoUsuario duser = new DaoUsuario();
    Usuario user = new Usuario();
    Conexion conn = new Conexion();
//    JScrollPane mibarra1;
    /**
     * Creates new form VerUSers
     */
    public VerUSers() {     
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        try{
          //Llamamos la variable de la tabla y le enviamos el modelo
            TablaUsers.setModel(modelo);
            //Prepara la consulta
            PreparedStatement ps = null;
            //Me permite ver los resultados
            ResultSet rs = null;
            java.sql.Connection con = conn.getConnection();
            //Creamos una consulta a nuestra tabla
            String sql = "SELECT idUsuario,Nombre,Apellido,Telefono,Direccion,Correo,Tipo,Estado,Ciudad,Contrato FROM usuario";
            //preparo la consulta con la variable de conexión
            ps = con.prepareStatement(sql);
            //Esta variable me devuelve el número de registros de la tabla
            rs = ps.executeQuery();
            //Pasamos los resultados de la consulta
            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            //Determino cuantos datos me arroja la consulta
            int cantidadColumnas = rsMd.getColumnCount();
            //agrego las columnas al modelo
                modelo.addColumn("Código");
                modelo.addColumn("Nombres");
                modelo.addColumn("Apellidos");
                modelo.addColumn("Telefono");
                modelo.addColumn("Direccion");
                modelo.addColumn("Correo");
                modelo.addColumn("Tipo");
                modelo.addColumn("Estado");
                modelo.addColumn("Ciudad");
                modelo.addColumn("Contrato");              
                //Establezco el ancho de las columnas del JTable
                int[] anchos = {50, 110, 110, 110,110,110,110,110,110,110,110,110};
                for (int i = 0; i < TablaUsers.getColumnCount(); i++)
                {
                    TablaUsers.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                }
                
                //Utilizo el while para recorrer los datos de la consulta
                while (rs.next())
                {
                    //Declaramos un arreglo de tipo objeto
                    Object[] filas = new Object[cantidadColumnas];
                    //Utilizamos un ciclo for para pasar todos los datos al tipo objeto
                      for (int i = 0; i < cantidadColumnas; i++)
                      {
                          filas[i] = rs.getObject(i + 1);
                      }
                      //agregamos los resultados al modelo
                        modelo.addRow(filas);
                }          
        }catch(SQLException ex)
        {
            System.err.println(ex.toString());
        }          
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsers = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbCiudad = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbContrato = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        textCod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Usuarios Registrados");

        TablaUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Nombre", "Apellido", "Telefono", "Dirección", "Correo", "Tipo", "Estado", "Ciudad", "Contrato"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsers);

        jLabel2.setText("Nombres");

        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellidos");

        txtApellido.setEnabled(false);

        jLabel4.setText("Teléfono");

        txttel.setEnabled(false);

        jLabel5.setText("Dirección");

        txtDir.setEnabled(false);

        jLabel6.setText("Correo");

        txtCorreo.setEnabled(false);

        jLabel7.setText("Tipo");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Administrador", "Empleado" }));
        cbTipo.setEnabled(false);

        jLabel8.setText("Estado");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Activo", "Inactivo" }));
        cbEstado.setEnabled(false);

        jLabel9.setText("Ciudad");

        cbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Bogota D.C", "Medellín", "Villavicencio", "Huila", "Barrancabermeja", "Meta" }));
        cbCiudad.setEnabled(false);

        jLabel10.setText("Contrato");

        cbContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Fijo", "Termino Indefinido", "Obra o Labor", "Aprendizaje", "Temporal", "Prestación de servicios" }));
        cbContrato.setEnabled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit.png"))); // NOI18N
        jButton1.setText("Editar");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/material.gif"))); // NOI18N
        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/undo.gif"))); // NOI18N
        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/broom (1).png"))); // NOI18N
        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setText("Codigo");

        textCod.setEnabled(false);
        textCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textCod, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbContrato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(9, 9, 9)
                                .addComponent(cbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel11)
                    .addComponent(textCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void TablaUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsersMouseClicked
        //Preparo la consulta
        this.jButton1.setEnabled(true);
        this.txtNombre.setEnabled(true);
        this.txtApellido.setEnabled(true);
        this.txttel.setEnabled(true);
        this.txtDir.setEnabled(true);
        this.txtCorreo.setEnabled(true);
        this.cbTipo.setEnabled(true);
        this.cbEstado.setEnabled(true);
        this.cbCiudad.setEnabled(true);
        this.cbContrato.setEnabled(true);
        PreparedStatement ps = null;
        ResultSet rs = null;
        try{       
                //Creamos un objeto para llamar la conexión
                Conexion cx = new Conexion();
                java.sql.Connection con = cx.getConnection();
                //Creo una variable que me capture el número de filas seleccionadas
                int Fila = TablaUsers.getSelectedRow();
                String codigo = TablaUsers.getValueAt(Fila, 0).toString();
                //Hago una consulta a la fila seleccionada y la almaceno en la variable ps
                ps = con.prepareStatement("SELECT idUsuario,Nombre,Apellido,Telefono,Direccion,Correo,Tipo,Estado,Ciudad,Contrato FROM usuario WHERE idUsuario=? ");
                ps.setString(1, codigo);              
                //Ejecuto la consulta
                rs = ps.executeQuery();
                //Recorro todas las filas de la tabla
                while (rs.next())
                {
                    textCod.setText(rs.getString(("idUsuario")));
                    txtNombre.setText(rs.getString("Nombre"));
                    txtApellido.setText(rs.getString("Apellido"));
                    txttel.setText(rs.getString("Telefono"));
                    txtDir.setText(rs.getString("Direccion"));
                    txtCorreo.setText(rs.getString("Correo"));
                    cbTipo.setSelectedItem(rs.getString("Tipo"));                   
                    cbEstado.setSelectedItem(rs.getString("Estado"));                    
                    cbCiudad.setSelectedItem(rs.getString("Ciudad"));              
                    cbContrato.setSelectedItem(rs.getString("Contrato"));
                }
            
            
        }catch(SQLException ex)
        {
            System.out.println(ex.toString() +"Evento clic tabla");
        }
    }//GEN-LAST:event_TablaUsersMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //almaceno en la variable int la fila seleccionada en el JTable
            
            int Fila = TablaUsers.getSelectedRow();
            if (textCod.getText().equals("") || txtNombre.getText().equals("") || txtApellido.getText().equals("") || txttel.getText().equals("") || txtDir.getText().equals("")
                || txtCorreo.getText().equals("") || cbTipo.equals("Seleccione...") || cbEstado.equals("Seleccione...") || cbCiudad.equals("Seleccione...")
                || cbContrato.equals("Seleccione...")) {
                    JOptionPane.showMessageDialog(null, "Por favor diligencie en su totalidad todos los campos para actualizar");           
            }else{
            //Preparo la consulta
            PreparedStatement ps = null;
            try{
                    java.sql.Connection con = conn.getConnection();
                    
                    ps = con.prepareStatement("UPDATE usuario SET Nombre=?,Apellido=?, Telefono=?, Direccion=?, Correo=?,Tipo=?, Estado=?, Ciudad=?, Contrato=? WHERE idUsuario=?");                   
                    ps.setString(1, txtNombre.getText()); 
                    ps.setString(2, txtApellido.getText());
                    ps.setString(3, txttel.getText());                  
                    ps.setString(4, txtDir.getText());
                    ps.setString(5, txtCorreo.getText());
                    ps.setString(6, cbTipo.getSelectedItem().toString());                   
                    ps.setString(7, cbEstado.getSelectedItem().toString());                                     
                    ps.setString(8, cbCiudad.getSelectedItem().toString());
                    ps.setString(9, cbContrato.getSelectedItem().toString());
                    ps.setString(10, textCod.getText());
                    ps.executeUpdate();
                    
                    /*el error radicaba en que el ps lo debo guardar en el mismo orden que los campos de la
                    consulta de actualizacion, no estabe en ese orden*/
                    
                    //Creo un mensaje si el cliente fue modificado en forma exitosa
                    JOptionPane.showMessageDialog(null, "Usuario actualizado correctamente");
                    //Realizo la actualizacion en cada uno de los campos
                    TablaUsers.setValueAt(textCod.getText(), Fila, 0);
                    TablaUsers.setValueAt(txtNombre.getText(), Fila, 1);
                    TablaUsers.setValueAt(txtApellido.getText(), Fila, 2);
                    TablaUsers.setValueAt(txttel.getText(), Fila, 3);
                    TablaUsers.setValueAt(txtDir.getText(), Fila, 4);                   
                    TablaUsers.setValueAt(txtCorreo.getText(), Fila, 5);
                    TablaUsers.setValueAt(cbTipo.getSelectedItem().toString(), Fila, 6);
                    TablaUsers.setValueAt(cbEstado.getSelectedItem().toString(), Fila, 7);
                    TablaUsers.setValueAt(cbCiudad.getSelectedItem().toString(), Fila, 8);
                    TablaUsers.setValueAt(cbContrato.getSelectedItem().toString(), Fila, 9);
                    limpiar();       
            }catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, "Error al Modificar usuario");
                System.out.println(ex);
            }
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void textCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Registrar nuevo
        this.hide();
        JOptionPane.showMessageDialog(null, "Debera regitrar antes un equipo y asignarlo a un usuario");
        RegistroInv inv = new RegistroInv();
        inv.show();        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerUSers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerUSers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerUSers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerUSers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerUSers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaUsers;
    private javax.swing.JComboBox<String> cbCiudad;
    private javax.swing.JComboBox<String> cbContrato;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textCod;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
private void limpiar()
    {
        this.jButton1.setEnabled(false);
        textCod.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txttel.setText("");
        txtDir.setText("");
        txtCorreo.setText("");  
        cbTipo.setSelectedItem("Seleccione...");
        cbEstado.setSelectedItem("Seleccione...");
        cbCiudad.setSelectedItem("Seleccione...");  
        cbContrato.setSelectedItem("Seleccione...");
    }
}
